### ISSUE TITLE
Alpha2 compains No module named 'src.mutils'

### ISSUE THREAD

**Issue by johnblommers** [iaacornus/simtex#5]
initially I had a working installation of alpha 1.

So I downloaded `simtex-0.2.0a0-py3-none-any.whl`  and  `requirements.txt` then

```bash
python3 -m pip install -r requirements.txt
python3 -m pip install simtex-0.2.0a0-py3-none-any.whl
```

There's no error produced so then:

```bash
simtex
Traceback (most recent call last):
  File "/home/johnb/.local/bin/simtex", line 5, in <module>
    from src.main import main
  File "/home/johnb/.local/lib/python3.10/site-packages/src/main.py", line 1, in <module>
    from src.cli import Cli
  File "/home/johnb/.local/lib/python3.10/site-packages/src/cli.py", line 6, in <module>
    from src.utils.config_fetch import ConfParse
  File "/home/johnb/.local/lib/python3.10/site-packages/src/utils/config_fetch.py", line 8, in <module>
    from src.mutils.fix_missing_conf import fix_missing_config
ModuleNotFoundError: No module named 'src.mutils'
```

I also tried downloading the source code and building/installing `simtex` that way. The `simtex` file installs into `/home/johnb/.local/bin/simtex`

So `simtex` cannot be used in this state.  Would you be able to offer any suggestions?

**Comment by iaacornus** [comment]
the error was due to paths specified `py_modeules` in setup.py which I forgot to update after restructuring the project, the new patch should fix it, as well as #4
