### ISSUE TITLE
The word LaTeX crashes simtex

### ISSUE THREAD

**Issue by johnblommers** [iaacornus/simtex#7]
When the input file contains the word LaTeX 
and we run the command:

`./simtex  -c  -i Ex1. md -T Ex1  -of  '.'  -f Ex1.tex  -a "Ex1"  -d "August 30, 2022"`

simtex crashes with:

```bash
Traceback (most recent call last):
  File "sre_parse.py", line 1051, in parse_template
KeyError: '\\L'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/main.py", line 12, in <module>
  File "src/main.py", line 8, in main
  File "src/cli.py", line 165, in cli
  File "src/cli.py", line 154, in <lambda>
  File "src/convert.py", line 56, in convert
  File "src/utils/tex/parser/body.py", line 107, in body
  File "src/utils/tex/text/format.py", line 86, in format
  File "re.py", line 209, in sub
  File "re.py", line 326, in _subx
  File "re.py", line 317, in _compile_repl
  File "sre_parse.py", line 1054, in parse_template
re.error: bad escape \L at position 0
[1146115] Failed to execute script 'main' due to unhandled exception!
```

Simtex does not crash when it sees LaTeX.  (LaTeX followed by a period)

Or if it sees \LaTeX

**Comment by iaacornus** [comment]
since the commit 3 days ago, I haven't experienced any error thrown regarding this issue in all of my assignments and lectures compiled that includes the same keyword, so I'm closing this.
